config/routes.rb
Rails.application.routes.draw do
  get 'filters_controller/create'

  get 'filters_controller/update'

  get 'sessions/create'

  get 'sessions/destroy'

  get 'welcome/index'
  
  get '/auth/dropbox_oauth2/authorize', to: 'dropbox#authorize'
  get '/auth/dropbox_oauth2/callback', to: 'dropbox#callback'

  get '/auth/evernote_oauth2/authorize', to: 'evernote#authorize'
  get '/auth/evernote_oauth2/callback', to: 'evernote#callback'
  
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  

  root 'welcome#index'

  resources :users
  resources :boards

  resources :widgets
  resources :sources
  resources :filters do
    member do
      post :change_check
    end
  end

  get 'boards/:id/search', to: 'boards#search'
  post 'boards/:id/search', to: 'boards#search'

  get 'dropbox_download/:id/:path', to: 'widgets#dropbox_download'
  match "/delayed_jobs" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  resources :sessions, only: [:create, :destroy]

end

app/models/board.rb
class Board < ActiveRecord::Base
  serialize :widgets, Array

  def auto_setup(current_user)
    puts "*********** AUTO SETUP ********"
    self.name = "Default"
    #@board.widgets = @clean_widgets
    source = Source.where(:user_id => current_user.id).first
    self.userid = current_user.id
    case source.provider
    when "google"
      #files
      widget = Widgets.new(name: "Files", userid: current_user.id, sources: [source.id], widget_type: "files")
      widget.save!
      self.widgets = [widget.id]
      #email
      widget = Widgets.new(name: "Email", userid: current_user.id, sources: [source.id], widget_type: "email")
      widget.save!
      self.widgets << widget.id
      #calendar
      widget = Widgets.new(name: "Calendar", userid: current_user.id, sources: [source.id], widget_type: "calendar")
      widget.save!
      self.widgets << widget.id
      #contacts
      #widget = Widgets.new(name: "Contacts", userid: current_user.id, sources: [source.id], widget_type: "contact")
      #widget.save!
      #self.widgets << widget.id
    when "evernote"
      #notes
      widget = Widgets.new(name: "Notes", userid: current_user.id, sources: [source.id], widget_type: "notes")
      widget.save!
      self.widgets << widget.id
    else
    end
    self.save!
  end
  
  def add_widget(widget)
    self.widgets << widget.id
    self.save!
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController

  skip_before_filter :verify_authenticity_token, only: [:add_filter, :edit_filter]

  def new
  end
  
  def create
    @board = Board.new(board_params)
    #@clean_widets = Array.new
    @board.widgets.reject! { |b| b.empty? }
    #@board.widgets = @clean_widgets
    @current_user ||= Users.find(session[:user_id]) if session[:user_id]
    @user_sources = Source.where(:user_id =>  @current_user.id).order(:provider)
    @board.userid = @current_user.id
    @board.save!
    redirect_to @board
  end
  
  def show
    p "========================boards_controller show====================="
    @current_user ||= Users.find(session[:user_id]) if session[:user_id]
    @board = Board.find(params[:id])
    @types_of_widgets = [['Email','email'],['Files','files'],['Contact','contact'],['Calendar','calendar'],['Notes','notes']]
    @filters = Filter.where(boardid: params[:id]).order("created_at ASC")
    p"=================filters : #{@filters}==============="
    if @board.userid.to_s == @current_user.id.to_s
      @widgets = Array.new
      @boards_list = @current_user.list_boards
      @board.widgets.each do |widget_id|
        @widgets.push(Widgets.find(widget_id))
      end
    else
      render :status => :forbidden, :text => "Forbidden fruit"
    end

  end
  
  def index
    @current_user ||= Users.find(session[:user_id]) if session[:user_id]
    @boards = Board.where(userid: @current_user.id)
  end

  def search
    @current_user ||= Users.find(session[:user_id]) if session[:user_id]
    puts "board parms: #{params}"
    @board = Board.find(params[:id])
    if @board.userid.to_s == @current_user.id.to_s
      @widgets = Array.new
      @boards_list = @current_user.list_boards
      @board.widgets.each do |widget_id|
        Widgets.find(widget_id).delay.search(params)
      end
    else
      render :status => :forbidden, :text => "Forbidden fruit"
    end
    redirect_to @board
  end

  def add_filter
    p "==================add_filter============"
    p "=========params : #{params}============"

    new_filter = Filter.new
    new_filter.filter = params[:filter_name]
    new_filter.widgetid = params[:widgetid]
    new_filter.boardid = params[:id]

    if new_filter.save
      data = {success:{filterid: new_filter.id, widgetid: new_filter.widgetid}}
    else
      data = {failure:{msg: new_filter.errors.full_messages.first}}
    end

    p "==============data : #{data}============="
    render json: data
  end

  def edit_filter
    p "=================edit_filter============"
    p "=================params : #{params}============"
    edit_filter = Filter.where(id: params[:filterid]).first;
    if edit_filter.nil?
      data = {failure: {msg: "Filter not found"}}
    else
      edit_filter.filter = params[:filter_name]
      if edit_filter.save
        data = {success:{msg: "Edit success!"}}
      else
        data = {failure:{msg: edit_filter.errors.full_messages.first}}
      end
    end

    render json: data
  end

  def del_filter
    p "=================del_filter============"
    p "=================params : #{params}============"
    Filter.where(filterid: params[:filterid]).destroy_all;
  end



  private
    def board_params
      params.require(:board).permit(:name, :widgets => [])
    end  
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/index.html.erb
<h1>Mashboard List</h1>
<table>
	<tr>
		<th>ID</th>
		<th>Name</th>
		<th>User ID</th>
	</tr>

	<% @boards.each do |board| %>
		<tr>
			<td><%= board.id %></td>
			<td><a href='<%= board.id %>'><%= board.name %></a></td>
			<td><%= board.userid %></td>
			<td><%= board.widgets %></td>
		</tr>
	<% end %>
</table>

app/views/boards/new.html.erb
<h1>Create a new Mashboard</h1>
<p>
	<%= form_for :board, url: boards_path  do |f| %>
		<p>
			<%= f.label :Name %>:
			<%= f.text_field :name%><br>
			Widgets:
			<%= f.collection_check_boxes :widgets, Widgets.order(:name), :id, :name %><br>
		</p>
 
		<p>
			<%= f.submit %>
		</p>
	<% end %>
</p>

app/views/boards/show.html.erb
<div ng-app='mashboard'>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
	<div class="container-fluid">
		<div class="navbar-header">
			<img src="/images/mashboard-logo.png" alt="Mashboard" id="mashboard-logo" />
			<span class="sr-only">Toggle navigation</span>
			</button>
		</div>
		<div class="navbar-collapse collapse">
			<form class="navbar-form search" action="<%=board_path%>/search" role="search" method="post">
		        <div style="display:none">
		          <input name="authenticity_token" type="hidden" value="<%=session[:_csrf_token]%>">
		        </div>
		        <div class="form-group">
		          <div class="input-group">
		            <input class="form-control" id="searchText" name="searchText" type="text" placeholder="Search" >
		            <span class="input-group-btn">
		              <button type="button" class="btn" onclick="javascript:searchWidgets();"><span class="fui-search"></span></button>
		            </span>
		          </div>
		        </div>
		    </form>
			<div id="top-right">
				<button type="button" class="btn btn-sm white-square" aria-label="Add Widget" data-toggle="modal" data-target=".board_add_widget-sm">
				  <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
				</button>
			</div>
		</div>
	</div>
</nav>

<div class="container-fluid">
	<div class="row">

        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
			<% @boards_list.each do |list_board|%>
				<% if list_board.id.to_i == params[:id].to_i%>
            		<li class="active"><a href="<%= list_board.id%>">
						<span class="icon mashboard-selected"></span><%= list_board.name%></a>
						<button class="btn btn-edit-nav" data-toggle="modal" data-target=".board_add_widget-sm">Edit</button>
					</li>
				<% else %>
            		<li><a href="<%= list_board.id%>"><span class="icon mashboard"></span><%= list_board.name%></a></li>
          		<% end %>
			<% end %>
		  </ul>
			<div id="account-dropdown" style=" " class="clearfix" >
				<% if current_user %>
					<img src="http://lorempixel.com/32/32/people/" class="pull-left" />
					<strong><%= @current_user.name %></strong>
					<small class="blue"><%= @current_user.email %></small>
				<% else %>
					<% if request.env['PATH_INFO'] != "/users/new"%>
							<%= link_to "Login to Mashboard", "/users/new", id: "sign_in" %>
						<% end %>
				<% end %>
			</div>
        </div>

		<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">

		<% @widgets.each do |widget|%>
			<%= render :partial => "widgets/widgets", :object => widget %>
		<% end %>

		</div>
	</div>
</div>

<div class="modal fade board_add_widget-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="false">
  	<div class="modal-dialog modal-sm">
    	<div class="modal-content">
		    <div class="modal-header">
		           <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
		           <h4 class="modal-title" id="myModalLabel">Add Widget</h4>
	        </div>
			<div class="modal-body">
				<%= form_for :widget, url: widgets_path  do |f| %>
					<div id="widget-name">
						<small><%= f.label :Name, "Widget Name"%></small>
						<%= f.text_field :name, :class=>"form-control input-hg"%><br>
					</div>
					<div class="dropdown margin-top">
						<small><%= f.label :Type, "Widget Type" %></small><br>
						<%= f.select :widget_type, @types_of_widgets %><br>
					</div>
					<div class="dropdown margin-top">
						<small><%= f.label :Source, "Initial Source" %></small><br>
						<%= f.collection_select :source, @user_sources, :id, :provider %><br>
					</div>
					<%= hidden_field_tag(:board, params[:id]) %>
					<%= f.submit("Add Widget", :class=>"btn btn-hg btn-primary margin-top-40") %>
				<% end %>
			</div>
		</div>
	</div>
</div>
<a href="#" class="reset"></a>
</div>